// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj7Ln9m-_YCvGIXhrNYCJpaQ4pm78-6Ts',
    appId: '1:468060583300:web:e594a65e0c32ede8c699d1',
    messagingSenderId: '468060583300',
    projectId: 'charity-circle-5f6f5',
    authDomain: 'charity-circle-5f6f5.firebaseapp.com',
    storageBucket: 'charity-circle-5f6f5.firebasestorage.app',
    measurementId: 'G-6CGF0FTEKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDQoL8FnNtwzxFLbpKKPhm-XC_FmN-u8',
    appId: '1:468060583300:android:504a4684bf13bc7ac699d1',
    messagingSenderId: '468060583300',
    projectId: 'charity-circle-5f6f5',
    storageBucket: 'charity-circle-5f6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuCDN67qzXmDFqyNVpeC2MPTmWGmJxotw',
    appId: '1:468060583300:ios:22e920fc468164c4c699d1',
    messagingSenderId: '468060583300',
    projectId: 'charity-circle-5f6f5',
    storageBucket: 'charity-circle-5f6f5.firebasestorage.app',
    iosBundleId: 'com.example.charityCircle',
  );
}
